// PageAudit: PDF report generator (HTML-based, browser print-to-PDF)
import type { AuditResult } from './analyzer'

export function generateReportHTML(result: AuditResult): string {
  const scoreColor = result.overallScore >= 70 ? '#16a34a' : result.overallScore >= 40 ? '#e6a23c' : '#ef4444'
  const date = new Date(result.timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const dimensionRows = result.dimensions.map((d) => {
    const barWidth = d.score * 10
    const barColor = d.score >= 7 ? '#16a34a' : d.score >= 4 ? '#e6a23c' : '#ef4444'
    return `
      <tr>
        <td style="padding:12px 16px;font-weight:600;border-bottom:1px solid #e2e8f0;">${d.name}</td>
        <td style="padding:12px 16px;border-bottom:1px solid #e2e8f0;">
          <div style="display:flex;align-items:center;gap:8px;">
            <div style="flex:1;height:8px;background:#f1f5f9;border-radius:4px;overflow:hidden;">
              <div style="width:${barWidth}%;height:100%;background:${barColor};border-radius:4px;"></div>
            </div>
            <span style="font-weight:600;color:${barColor};min-width:30px;">${d.score}/10</span>
          </div>
        </td>
        <td style="padding:12px 16px;border-bottom:1px solid #e2e8f0;font-size:13px;color:#64748b;">
          ${d.suggestions.slice(0, 2).map((s) => `• ${s}`).join('<br/>')}
        </td>
      </tr>`
  }).join('')

  const topActionsHTML = result.topActions.map((a, i) =>
    `<div style="display:flex;align-items:flex-start;gap:12px;padding:12px 0;border-bottom:1px solid #f1f5f9;">
      <span style="width:28px;height:28px;border-radius:50%;background:#f59e0b;color:white;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:13px;flex-shrink:0;">${i + 1}</span>
      <span style="font-size:14px;color:#1e293b;line-height:1.5;">${a}</span>
    </div>`
  ).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PageAudit Report - ${result.url}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1e293b; margin: 0; padding: 40px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div style="max-width:800px;margin:0 auto;">
    <!-- Header -->
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:32px;">
      <div>
        <h1 style="margin:0;font-size:24px;color:#1e293b;">PageAudit Report</h1>
        <p style="margin:4px 0 0;font-size:14px;color:#64748b;">${date}</p>
      </div>
      <div style="text-align:right;">
        <div style="font-size:12px;color:#64748b;">Analyzed URL</div>
        <a href="${result.url}" style="font-size:14px;color:#3b82f6;text-decoration:none;word-break:break-all;">${result.url}</a>
      </div>
    </div>

    <!-- Overall Score -->
    <div style="text-align:center;padding:32px;background:#f8fafc;border-radius:16px;margin-bottom:32px;">
      <div style="font-size:64px;font-weight:800;color:${scoreColor};line-height:1;">${result.overallScore}</div>
      <div style="font-size:14px;color:#64748b;margin-top:8px;">Overall Score / 100</div>
      <p style="font-size:14px;color:#475569;margin-top:16px;max-width:500px;margin-left:auto;margin-right:auto;line-height:1.6;">${result.summary}</p>
    </div>

    <!-- Dimension Scores -->
    <h2 style="font-size:18px;margin-bottom:16px;">Dimension Scores</h2>
    <table style="width:100%;border-collapse:collapse;margin-bottom:32px;">
      <thead>
        <tr style="background:#f8fafc;">
          <th style="padding:10px 16px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase;border-bottom:2px solid #e2e8f0;">Dimension</th>
          <th style="padding:10px 16px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase;border-bottom:2px solid #e2e8f0;">Score</th>
          <th style="padding:10px 16px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase;border-bottom:2px solid #e2e8f0;">Key Suggestions</th>
        </tr>
      </thead>
      <tbody>${dimensionRows}</tbody>
    </table>

    <!-- Top Actions -->
    <h2 style="font-size:18px;margin-bottom:16px;">Top Priority Actions</h2>
    <div style="margin-bottom:32px;">${topActionsHTML}</div>

    <!-- Footer -->
    <div style="text-align:center;padding:20px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8;">
      Generated by PageAudit — AI Landing Page CRO Analyzer<br/>
      tools.ovanime.com/page-audit
    </div>
  </div>
</body>
</html>`
}

/** Open report in new window for printing/PDF saving */
export function openReportForPrint(result: AuditResult): void {
  const html = generateReportHTML(result)
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const win = window.open(url, '_blank')
  if (win) {
    win.onload = () => {
      setTimeout(() => win.print(), 500)
    }
  }
}
