'use client'
import { useState, useMemo } from 'react'
import { getToolBySlug } from '@/lib/tools'
import ToolLayout from '@/components/ToolLayout'

const tool = getToolBySlug('htaccess-generator')!

interface RedirectRule { from: string; to: string; type: '301' | '302' }

export default function HtaccessGenerator() {
  const [https, setHttps] = useState(true)
  const [www, setWww] = useState<'add' | 'remove' | 'none'>('remove')
  const [trailingSlash, setTrailingSlash] = useState<'add' | 'remove' | 'none'>('none')
  const [customError404, setCustomError404] = useState('/404.html')
  const [customError500, setCustomError500] = useState('')
  const [enableGzip, setEnableGzip] = useState(true)
  const [enableCache, setEnableCache] = useState(true)
  const [cacheDays, setCacheDays] = useState('30')
  const [securityHeaders, setSecurityHeaders] = useState(true)
  const [directoryListing, setDirectoryListing] = useState(false)
  const [redirects, setRedirects] = useState<RedirectRule[]>([])
  const [newRedirect, setNewRedirect] = useState<RedirectRule>({ from: '/old-page', to: '/new-page', type: '301' })
  const [copied, setCopied] = useState(false)

  const addRedirect = () => {
    if (newRedirect.from && newRedirect.to) {
      setRedirects([...redirects, { ...newRedirect }])
      setNewRedirect({ from: '', to: '', type: '301' })
    }
  }
  const removeRedirect = (i: number) => setRedirects(redirects.filter((_, idx) => idx !== i))

  const output = useMemo(() => {
    const lines: string[] = []
    lines.push('# Generated by DevTools Hub htaccess Generator')
    lines.push('# https://devtools-hub.com/tools/htaccess-generator')
    lines.push('')

    // HTTPS redirect
    if (https) {
      lines.push('# Force HTTPS')
      lines.push('RewriteEngine On')
      lines.push('RewriteCond %{HTTPS} off')
      lines.push('RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]')
      lines.push('')
    }

    // WWW
    if (www === 'remove') {
      lines.push('# Remove www')
      lines.push('RewriteEngine On')
      lines.push('RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]')
      lines.push('RewriteRule ^(.*)$ https://%1/$1 [R=301,L]')
      lines.push('')
    } else if (www === 'add') {
      lines.push('# Force www')
      lines.push('RewriteEngine On')
      lines.push('RewriteCond %{HTTP_HOST} !^www\\. [NC]')
      lines.push('RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]')
      lines.push('')
    }

    // Trailing slash
    if (trailingSlash === 'remove') {
      lines.push('# Remove trailing slash')
      lines.push('RewriteEngine On')
      lines.push('RewriteCond %{REQUEST_FILENAME} !-d')
      lines.push('RewriteRule ^(.*)/$ /$1 [R=301,L]')
      lines.push('')
    } else if (trailingSlash === 'add') {
      lines.push('# Force trailing slash')
      lines.push('RewriteEngine On')
      lines.push('RewriteCond %{REQUEST_FILENAME} !-f')
      lines.push('RewriteCond %{REQUEST_URI} !(.*)/$')
      lines.push('RewriteRule ^(.*)$ $1/ [R=301,L]')
      lines.push('')
    }

    // Custom error pages
    if (customError404) {
      lines.push('# Custom Error Pages')
      lines.push(`ErrorDocument 404 ${customError404}`)
      if (customError500) lines.push(`ErrorDocument 500 ${customError500}`)
      lines.push('')
    }

    // Redirects
    if (redirects.length > 0) {
      lines.push('# Redirects')
      for (const r of redirects) {
        lines.push(`Redirect ${r.type} ${r.from} ${r.to}`)
      }
      lines.push('')
    }

    // Gzip compression
    if (enableGzip) {
      lines.push('# Gzip Compression')
      lines.push('<IfModule mod_deflate.c>')
      lines.push('  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css')
      lines.push('  AddOutputFilterByType DEFLATE application/javascript application/json')
      lines.push('  AddOutputFilterByType DEFLATE application/xml application/xhtml+xml')
      lines.push('  AddOutputFilterByType DEFLATE image/svg+xml application/x-font-woff')
      lines.push('</IfModule>')
      lines.push('')
    }

    // Browser caching
    if (enableCache) {
      const seconds = parseInt(cacheDays) * 86400
      lines.push('# Browser Caching')
      lines.push('<IfModule mod_expires.c>')
      lines.push('  ExpiresActive On')
      lines.push(`  ExpiresByType image/jpeg "access plus ${cacheDays} days"`)
      lines.push(`  ExpiresByType image/png "access plus ${cacheDays} days"`)
      lines.push(`  ExpiresByType image/webp "access plus ${cacheDays} days"`)
      lines.push(`  ExpiresByType image/svg+xml "access plus ${cacheDays} days"`)
      lines.push(`  ExpiresByType text/css "access plus ${cacheDays} days"`)
      lines.push(`  ExpiresByType application/javascript "access plus ${cacheDays} days"`)
      lines.push(`  ExpiresByType application/x-font-woff "access plus ${cacheDays} days"`)
      lines.push('</IfModule>')
      lines.push('')
      lines.push('<IfModule mod_headers.c>')
      lines.push(`  Header set Cache-Control "max-age=${seconds}, public"`)
      lines.push('</IfModule>')
      lines.push('')
    }

    // Security headers
    if (securityHeaders) {
      lines.push('# Security Headers')
      lines.push('<IfModule mod_headers.c>')
      lines.push('  Header set X-Content-Type-Options "nosniff"')
      lines.push('  Header set X-Frame-Options "SAMEORIGIN"')
      lines.push('  Header set X-XSS-Protection "1; mode=block"')
      lines.push('  Header set Referrer-Policy "strict-origin-when-cross-origin"')
      lines.push('  Header set Permissions-Policy "camera=(), microphone=(), geolocation=()"')
      lines.push('</IfModule>')
      lines.push('')
    }

    // Directory listing
    if (!directoryListing) {
      lines.push('# Disable Directory Listing')
      lines.push('Options -Indexes')
      lines.push('')
    }

    return lines.join('\n')
  }, [https, www, trailingSlash, customError404, customError500, enableGzip, enableCache, cacheDays, securityHeaders, directoryListing, redirects])

  const copy = () => {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const download = () => {
    const blob = new Blob([output], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = '.htaccess'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <ToolLayout tool={tool}>
      <div style={{ maxWidth: '1000px', margin: '0 auto', padding: '24px 16px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 700, textAlign: 'center', marginBottom: '8px' }}>htaccess Generator</h1>
        <p style={{ textAlign: 'center', color: '#64748b', marginBottom: '24px', fontSize: '14px' }}>
          Generate Apache .htaccess rules for redirects, security headers, and caching
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
          {/* Options */}
          <div>
            {/* Redirects section */}
            <div style={{ marginBottom: '20px', padding: '16px', backgroundColor: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
              <h3 style={{ fontSize: '14px', fontWeight: 600, marginBottom: '12px' }}>URL & Redirects</h3>
              {[
                { label: 'Force HTTPS', checked: https, onChange: () => setHttps(!https) },
                { label: 'Disable Directory Listing', checked: !directoryListing, onChange: () => setDirectoryListing(!directoryListing) },
              ].map(opt => (
                <label key={opt.label} style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px', cursor: 'pointer', fontSize: '13px' }}>
                  <input type="checkbox" checked={opt.checked} onChange={opt.onChange} style={{ accentColor: '#3b82f6' }} />
                  {opt.label}
                </label>
              ))}
              <div style={{ marginBottom: '8px' }}>
                <label style={{ fontSize: '12px', fontWeight: 600, color: '#64748b' }}>WWW handling:</label>
                <select value={www} onChange={(e) => setWww(e.target.value as 'add' | 'remove' | 'none')}
                  style={{ display: 'block', marginTop: '4px', padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '13px', width: '100%' }}>
                  <option value="remove">Remove www</option>
                  <option value="add">Force www</option>
                  <option value="none">No change</option>
                </select>
              </div>
              <div style={{ marginBottom: '8px' }}>
                <label style={{ fontSize: '12px', fontWeight: 600, color: '#64748b' }}>Trailing slash:</label>
                <select value={trailingSlash} onChange={(e) => setTrailingSlash(e.target.value as 'add' | 'remove' | 'none')}
                  style={{ display: 'block', marginTop: '4px', padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '13px', width: '100%' }}>
                  <option value="remove">Remove trailing slash</option>
                  <option value="add">Force trailing slash</option>
                  <option value="none">No change</option>
                </select>
              </div>
              <div style={{ display: 'flex', gap: '8px', marginBottom: '8px' }}>
                <div style={{ flex: 1 }}>
                  <label style={{ fontSize: '12px', fontWeight: 600, color: '#64748b' }}>404 page:</label>
                  <input value={customError404} onChange={(e) => setCustomError404(e.target.value)}
                    style={{ width: '100%', padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '13px', marginTop: '4px', boxSizing: 'border-box' }} />
                </div>
                <div style={{ flex: 1 }}>
                  <label style={{ fontSize: '12px', fontWeight: 600, color: '#64748b' }}>500 page:</label>
                  <input value={customError500} onChange={(e) => setCustomError500(e.target.value)} placeholder="optional"
                    style={{ width: '100%', padding: '6px 10px', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '13px', marginTop: '4px', boxSizing: 'border-box' }} />
                </div>
              </div>
            </div>

            {/* Redirects */}
            <div style={{ marginBottom: '20px', padding: '16px', backgroundColor: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
              <h3 style={{ fontSize: '14px', fontWeight: 600, marginBottom: '12px' }}>Custom Redirects</h3>
              {redirects.map((r, i) => (
                <div key={i} style={{ display: 'flex', gap: '4px', alignItems: 'center', marginBottom: '4px', fontSize: '12px' }}>
                  <span style={{ fontFamily: 'monospace', color: '#ef4444' }}>{r.type}</span>
                  <span style={{ fontFamily: 'monospace' }}>{r.from}</span>
                  <span style={{ color: '#94a3b8' }}>→</span>
                  <span style={{ fontFamily: 'monospace', color: '#10b981' }}>{r.to}</span>
                  <button onClick={() => removeRedirect(i)} style={{ marginLeft: 'auto', border: 'none', background: 'none', cursor: 'pointer', color: '#94a3b8', fontSize: '12px' }}>✕</button>
                </div>
              ))}
              <div style={{ display: 'flex', gap: '4px', marginTop: '8px' }}>
                <select value={newRedirect.type} onChange={(e) => setNewRedirect({ ...newRedirect, type: e.target.value as '301' | '302' })}
                  style={{ padding: '4px', border: '1px solid #e2e8f0', borderRadius: '4px', fontSize: '12px' }}>
                  <option value="301">301</option>
                  <option value="302">302</option>
                </select>
                <input value={newRedirect.from} onChange={(e) => setNewRedirect({ ...newRedirect, from: e.target.value })} placeholder="/old"
                  style={{ flex: 1, padding: '4px 8px', border: '1px solid #e2e8f0', borderRadius: '4px', fontSize: '12px', fontFamily: 'monospace' }} />
                <input value={newRedirect.to} onChange={(e) => setNewRedirect({ ...newRedirect, to: e.target.value })} placeholder="/new"
                  style={{ flex: 1, padding: '4px 8px', border: '1px solid #e2e8f0', borderRadius: '4px', fontSize: '12px', fontFamily: 'monospace' }} />
                <button onClick={addRedirect} style={{ padding: '4px 8px', backgroundColor: '#3b82f6', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '12px' }}>+</button>
              </div>
            </div>

            {/* Performance */}
            <div style={{ padding: '16px', backgroundColor: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
              <h3 style={{ fontSize: '14px', fontWeight: 600, marginBottom: '12px' }}>Performance & Security</h3>
              {[
                { label: 'Enable Gzip Compression', checked: enableGzip, onChange: () => setEnableGzip(!enableGzip) },
                { label: 'Enable Browser Caching', checked: enableCache, onChange: () => setEnableCache(!enableCache) },
                { label: 'Security Headers (XSS, CSRF, etc.)', checked: securityHeaders, onChange: () => setSecurityHeaders(!securityHeaders) },
              ].map(opt => (
                <label key={opt.label} style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px', cursor: 'pointer', fontSize: '13px' }}>
                  <input type="checkbox" checked={opt.checked} onChange={opt.onChange} style={{ accentColor: '#3b82f6' }} />
                  {opt.label}
                </label>
              ))}
              {enableCache && (
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginLeft: '24px' }}>
                  <label style={{ fontSize: '12px', color: '#64748b' }}>Cache duration:</label>
                  <input type="number" value={cacheDays} onChange={(e) => setCacheDays(e.target.value)} min="1" max="365"
                    style={{ width: '60px', padding: '4px 8px', border: '1px solid #e2e8f0', borderRadius: '4px', fontSize: '12px' }} />
                  <span style={{ fontSize: '12px', color: '#64748b' }}>days</span>
                </div>
              )}
            </div>
          </div>

          {/* Output */}
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span style={{ fontSize: '14px', fontWeight: 600 }}>.htaccess Output</span>
              <div style={{ display: 'flex', gap: '8px' }}>
                <button onClick={copy} style={{ padding: '4px 12px', backgroundColor: '#3b82f6', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '13px' }}>{copied ? '✓ Copied!' : 'Copy'}</button>
                <button onClick={download} style={{ padding: '4px 12px', backgroundColor: '#10b981', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '13px' }}>Download</button>
              </div>
            </div>
            <pre style={{ padding: '16px', backgroundColor: '#1e293b', color: '#e2e8f0', borderRadius: '12px', fontSize: '12px', fontFamily: 'monospace', lineHeight: 1.5, minHeight: '500px', overflow: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
              {output}
            </pre>
          </div>
        </div>
      </div>
    </ToolLayout>
  )
}
